hydra:
  run:
    dir: /data/data/malpolon/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: false
  checkpoint_path: # "/data/data/malpolon/outputs/glc24_cnn_multimodal_ensemble/runOK_2024-08-12_11-50-01/last.ckpt"

data:
  root: "/data/data/malpolon/"
  data_paths:
    train:
      envdata_dir:  "${data.root}inputs/npy-norm/"
  metadata_paths:
    train:  "${data.root}database.csv"
  num_classes: &num_classes 1796
  download_data: True
  train_batch_size: 64
  inference_batch_size: 16
  num_workers: 16

task:
  task: "classification_multilabel" # ['classification_binary', 'classification_multiclass', 'classification_multilabel']

trainer:
  accelerator: "gpu"
  devices: 'auto'
  max_epochs: 20
  val_check_interval: 100
  check_val_every_n_epoch: 1
  # log_every_n_steps: 100

model:
  provider_name: "malpolon" # choose from ["malpolon", "timm", "torchvision"]
  model_name: "glc24_multimodal_ensemble"
  model_kwargs:
    pretrained: true # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
  modifiers:
    change_last_layer:
      num_outputs: *num_classes

optimizer:
  lr: 0.00025
  weight_decay: 0
  momentum: 0.9
  nesterov: true
  loss_kwargs:
    pos_weight: 10.0
  metrics:
    multilabel_accuracy:
      # callable: 'Fmetrics.classification.multilabel_accuracy'
      kwargs:
        num_labels: *num_classes
        # threshold: 0.1
        average: micro
    multilabel_recall:
      callable: 'Fmetrics.classification.multilabel_recall'
      kwargs:
        num_labels: *num_classes
        # threshold: 0.1
        average: micro
    multilabel_precision:
      callable: 'Fmetrics.classification.multilabel_precision'
      kwargs:
        num_labels: *num_classes
        # threshold: 0.1
        average: micro
    multilabel_f1-score:
      callable: 'Fmetrics.classification.multilabel_f1_score'
      kwargs:
        num_labels: *num_classes
        # threshold: 0.1
        average: micro

loggers:
  exp_name: "1_env_rasters_only"  # Name of your experiment
  log_dir_name: "/data/data/malpolon/logs"  # Name of the logs directory
