hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: false
  checkpoint_path:

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: 'gpu'
  devices: 'auto'
  max_epochs: 10
  val_check_interval: 5
  log_every_n_steps: 10

model:
  provider_name: "torchvision"
  model_name: "resnet50"
  model_kwargs:
    pretrained: true
  modifiers:
    change_last_layer:
      num_outputs: 100

optimizer:
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true
  metrics:
    multiclass_accuracy:
      kwargs:
        num_classes: 100
    top_30_multiclass_accuracy:  # Top-30 accuracy
      callable: "Fmetrics.classification.multiclass_accuracy"
      kwargs:
        top_k: 30
        num_classes: 100

data:
  dataset_path: "dataset/"
  minigeolifeclef: true
  train_batch_size: 32
  inference_batch_size: 256
  num_workers: 8

task:
  task: 'classification_multiclass'  # ['classification_binary', 'classification_multiclass', 'classification_multilabel']

loggers:
  exp_name: "resnet50_glc22"  # Name of your experiment
  log_dir_name: "tensorboard_logs/"  # Name of the logs directory
