hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: 'gpu'
  # devices: 1
  max_epochs: 10
  # val_check_interval: 10
  check_val_every_n_epoch: 1

run:
  predict: false
  checkpoint_path:   # Relative to hydra.run.dir

model:
  provider_name: "timm"  # choose from ["timm", "torchvision"]
  model_name: "inception_v3"
  model_kwargs:
    pretrained: false  # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
    num_classes:
    in_chans:
    output_stride:
    global_pool:
    drop_rate: 0.5
  modifiers:
    change_first_convolutional_layer:
     num_input_channels: 4
    change_last_layer:
      num_outputs: 5

optimizer:
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: false
  metrics:
    # binary_accuracy:
    #   # callable: 'Fmetrics.accuracy'
    #   kwargs: {}
    # multiclass_accuracy:
    #   # callable: 'Fmetrics.classification.multiclass_accuracy'
    #   kwargs:
    #     num_classes: 5
    multiclass_accuracy:  # Top-3 accuracy 
      # callable: 'Fmetrics.classification.multiclass_accuracy'
      kwargs:
        top_k: 3
        num_classes: 5
    # r_precision:
    #   kwargs:
    # multilabel_accuracy:
    #   # callable: 'Fmetrics.classification.multilabel_accuracy'
    #   kwargs:
    #     num_labels: 5

data:
  dataset_path: "../../../dataset/"  # Relative to hydra.run.dir
  labels_name: ???
  download_data_sample: False
  train_batch_size: 8
  inference_batch_size: 2
  num_workers: 0
  units: "pixel"
  crs: 4326 

task:
  task: 'classification_multiclass'  # ['classification_binary', 'classification_multiclass', 'classification_multilabel']  
