defaults:
  - cnn_on_rgb_patches_config

run:
  predict: false
  checkpoint_path:

data:
  num_classes: &num_classes 10
  dataset_path: "dataset/"
  train_batch_size: 32

model:
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 4
      new_conv_layer_init_func:
        _target_: cnn_on_rgb_nir_patches.NewConvolutionalLayerInitFuncStrategy
        strategy: "red_pretraining"
        rescaling: true
    change_last_layer:
      num_outputs: *num_classes


loggers:
  exp_name: "resnet18_rgb-nir_microglc22"  # Name of your experiment