hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: 'gpu'
  devices: 'auto'
  max_epochs: 50
  # val_check_interval: 10
  check_val_every_n_epoch: 1

run:
  predict: true
  checkpoint_path: "outputs/cnn_on_rgbnir_glc23_patches_multilabel/2024-02-21_17-40-10/checkpoint-epoch=02-step=39-val_multilabel_accuracy=0.6204.ckpt"

model:
  provider_name: "timm"  # choose from ["timm", "torchvision"]
  model_name: "resnet18"
  model_kwargs:
    pretrained: true  # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
    num_classes:
    in_chans:
    output_stride:
    global_pool:
  modifiers:
    change_first_convolutional_layer:
     num_input_channels: 4
    change_last_layer:
      num_outputs: 96

optim:
  optimizer:
    sgd:  # ['adam', 'sgd', 'adamw', 'adadelta', 'adagrad', 'adamax', 'rmsprop']
      # callable: 'optim.SGD'
      kwargs:
        lr: 1e-2
        weight_decay: 0
        momentum: 0.9
        nesterov: true
  metrics:
    multilabel_accuracy:
      # callable: 'Fmetrics.classification.multilabel_accuracy'
      kwargs:
        num_labels: 96
    multilabel_recall:
      callable: 'Fmetrics.classification.multilabel_recall'
      kwargs:
        num_labels: 96
    multilabel_f1_score_macro:
      callable: 'Fmetrics.classification.multilabel_f1_score'
      kwargs:
        num_labels: 96
        average: 'macro'

data:
  dataset_path: "dataset/sample_data/"
  labels_name: "dataset/sample_data/Presence_only_occurrences/Presences_only_train_sample_mutilabel_dummy.csv"
  train_batch_size: 8
  inference_batch_size: 2
  num_workers: 8
  units: "pixel"
  crs: 4326

task:
  task: 'classification_multiclass'  # ['classification_binary', 'classification_multiclass', 'classification_multilabel']
