name: Python Test

on:
  push:
      branches:
        - main
        - dev
        - dev-ci-doc
      paths:
        - '**.py'
        - '!docs/**'

jobs:
    test:
        name: Unit Test 
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4   
              name: Setup python ${{ matrix.python-version }}
              with:
                cache-dependency-path: '**/requirements_python3.10.txt'
                python-version: ${{ matrix.python-version }}
                cache: 'pip' # caching pip dependencies
            - name: install cartopy system packages
              run: sudo apt-get install libgeos-dev
            - name: pip install -r requirements_python3.10.txt
              run: pip install -r ./requirements_python3.10.txt
            - name: pip install -e .
              run: pip install -e .
            - name: Pytest
              run: python -m pytest 
